version: "3.8"
services:
  inference:
    build:
      context: .
      dockerfile: docker/inference.Dockerfile
    container_name: inference
    ports: ["8091:8091"]
  dispatcher:
    build:
      context: .
      dockerfile: docker/dispatcher.Dockerfile
    container_name: dispatcher
    environment:
      - INFERENCE_BACKENDS=inference:8091
    ports: ["8090:8090"]
    depends_on: [inference]
  gateway:
    build:
      context: .
      dockerfile: docker/gateway.Dockerfile
    container_name: gateway
    environment:
      - INFERENCE_BACKENDS=inference:8091
    ports: ["8080:8080"]
    depends_on: [dispatcher, inference]
  ingest:
    build:
      context: .
      dockerfile: docker/ingest.Dockerfile
    container_name: ingest
    environment:
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=8080
      - STREAM_ID=demo_stream
    depends_on: [gateway]
